Provide a convenience API for dispatching blocking work (#1563)
apple/swift-nio pull request #1662
Opened 2020-09-29 13:20 UTC by gcjenkinson

Motivation:

SwiftNIO lacks a convenience API for performing blocking IO / tasks. As
this is a fairl common task it then requires the clients to make ad hoc
implementations that address this requirement.

Modifications:

Extension to DispatchQueue with the following method to schedule a work
item to the `DispatchQueue` and return and `EventLoopFuture` for the
result returned:

- `asyncWithFuture<NewValue>(on loop: EventLoop, _ callbackMayBlock: @escaping () throws -> NewValue) -> EventLoopFuture<NewValue>`

Added new unit test for this function.

Extention to EventLoopFuture with the following functions:

- `flatMapBlocking<NewValue)(onto queue DispatchQueue, _ callbackMayBlock: @escpaing (Value) throws -> NewValue) -> EventLoopFuture<NewValue>`
- `whenSuccessBlocking(onto queue DispatchQueue, _ callbackMayBlock: @escpaing (Value) -> Void) -> EventLoopFuture<NewValue>`
- `whenFailureBlocking()onto queue DispatchQueue, _ callbackMayBlock: @escpaing (Error) -> Void) -> EventLoopFuture<NewValue>`
- `whenCompleteBlocking(onto queue DispatchQueue, _ callbackMayBlock: @escpaing (Result<Value, Error>) -> Void) -> EventLoopFuture<NewValue>`

These functions may all be called safely with callbacks that perform blocking IO / Tasks.

Added new unit tests to EventLoopFutureTest.swift for each new function.

Result:

New public API for `EventLoopFuture` that allows scheduling of blocking IO / Tasks.

2020-09-29 14:26 UTC, glbrntt requested changes
This looks pretty good! I've left a few nits and comments.

2020-09-29 14:26 UTC, glbrntt commented on Sources/NIO/DispathQueue+WithFuture.swift
> +        }
```suggestion
        }

```

2020-09-29 14:26 UTC, glbrntt commented on Sources/NIO/EventLoopFuture.swift
> +    func flatMapBlocking<NewValue>(onto queue: DispatchQueue, _ callbackMayBlock: @escaping (Value) throws -> NewValue)
public!

2020-09-29 14:26 UTC, glbrntt commented on Sources/NIO/DispathQueue+WithFuture.swift
> +    func asyncWithFuture<NewValue>(on loop: EventLoop, _ callbackMayBlock: @escaping () throws -> NewValue)
also if a signature is too long for one line we typically break on parameters and keep the return statement on the same line as the last parameter:

```swift
func asyncWithFuture<NewValue>(on loop: EventLoop, 
                               _ callbackMayBlock: @escaping () throws -> NewValue) -> EventLoopFuture<NewValue> {
    ...
}
```

2020-09-29 14:26 UTC, glbrntt commented on Sources/NIO/EventLoopFuture.swift
> +    /// promise.futureResult.flatMap(onto: DispatchQueue.global()) { value in Int
```suggestion
    /// promise.futureResult.flatMapBlocking(onto: DispatchQueue.global()) { value in
```

2020-09-29 14:26 UTC, glbrntt commented on Sources/NIO/EventLoopFuture.swift
> +        self._whenComplete {
Why not just use `self.whenSuccess` here?

2020-09-29 14:26 UTC, glbrntt commented on Sources/NIO/EventLoopFuture.swift
> +        self._whenComplete {
Same here, why not just `self.whenFailure`?

2020-09-29 14:26 UTC, glbrntt commented on Sources/NIO/EventLoopFuture.swift
> +        self._whenComplete {
Same here, why not just use `self.whenComplete`?

2020-09-29 14:26 UTC, glbrntt commented on Tests/NIOTests/DispatchQueue+WithFutureTest.swift
> +@testable import NIO
This shouldn't need to be `@testable`

2020-09-29 14:26 UTC, glbrntt commented on Tests/NIOTests/DispatchQueue+WithFutureTest.swift
> +    func testDispatchQueueAsyncWithFuture() {
We should add a test for when the callback throws as well.

2020-09-30 08:57 UTC, gcjenkinson commented on Sources/NIO/DispathQueue+WithFuture.swift
> +    func asyncWithFuture<NewValue>(on loop: EventLoop, _ callbackMayBlock: @escaping () throws -> NewValue)
If I run the code through `swift-format` (with 4 spaces indent) it formats this as

```
public func asyncWithFuture<NewValue>(
    loop: EventLoop,
    _ callbackMayBlock: @escaping () throws -> NewValue
 ) -> EventLoopFuture<NewValue> {
```

Is this fine?

2020-09-30 09:24 UTC, glbrntt commented on Sources/NIO/DispathQueue+WithFuture.swift
> +    func asyncWithFuture<NewValue>(on loop: EventLoop, _ callbackMayBlock: @escaping () throws -> NewValue)
We don't use `swift-format` at the moment, we will eventually. For now I'd rather additions were consistent with the existing style.

2020-09-30 09:27 UTC, gcjenkinson commented on Sources/NIO/DispathQueue+WithFuture.swift
> +    func asyncWithFuture<NewValue>(on loop: EventLoop, _ callbackMayBlock: @escaping () throws -> NewValue)
I should have said -> The reason I'm asking is with adding the missing public, aligning the parameters on the line wrap puts the second line over 120 characters.

2020-09-30 09:39 UTC, glbrntt commented on Sources/NIO/DispathQueue+WithFuture.swift
> +    func asyncWithFuture<NewValue>(on loop: EventLoop, _ callbackMayBlock: @escaping () throws -> NewValue)
Oh okay, that's fine then.

2020-09-30 10:34 UTC, Lukasa commented on Sources/NIO/EventLoopFuture.swift
> +    /// promise.futureResult.flatMapBlocking(onto: DispatchQueue.global()) { value in Int
Same note here about code block formatting.

2020-09-30 10:34 UTC, Lukasa commented on Sources/NIO/EventLoopFuture.swift
> +        self.whenSuccess{ value in
```suggestion
        self.whenSuccess { value in
```

2020-09-30 10:34 UTC, Lukasa commented on Sources/NIO/EventLoopFuture.swift
> +        self.whenFailure{ err in
```suggestion
        self.whenFailure { err in
```

2020-09-30 12:41 UTC, Lukasa approved these changes
LGTM, nice!

2020-09-30 12:48 UTC, glbrntt approved these changes

2020-09-30 12:49 UTC, glbrntt commented
We have a few conflicts with `main` which need resolving now @gcjenkinson -- looks great otherwise

2020-09-30 12:50 UTC, gcjenkinson commented
No worries. I'll fix up shortly.

2020-09-30 16:04 UTC, merged