Add multiple channel handlers in a single async call.
apple/swift-nio pull request #1683
Opened 2020-10-23 20:28 UTC by PeterAdams-A

Motivation:

Curently adding multiple channel handlers makes a call to the
async version of addHandler for each handler resulting in
n+1 futures.  It feels better to use just one future and add
all the handlers synchoronously.

Modifications:

Change sync functions with take a promise to instead return a Result.
Feed this back until reaching addHandlers.

Result:

Multiple handlers can be added more quickly.

_[One line description of your change]_

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications:

_[Describe the modifications you've done.]_

### Result:

_[After your change, what will change.]_

2020-10-23 20:29 UTC, PeterAdams-A commented
Code looks a bit worse but I think it should run better.

2020-10-24 07:26 UTC, Lukasa requested changes
I’m broadly happy with this! I have a couple of basic notes but otherwise this seems like a good change.

2020-10-24 07:26 UTC, Lukasa commented on Sources/NIO/ChannelPipeline.swift
> +            }.reduce(.success(()), firstErrorOrSuccess)
Let’s avoid map and reduce here and just use a loop, we don’t need the intermediate arrays and if we’re aiming to speed things up anyway it’s another incremental savings.

2020-10-24 07:26 UTC, Lukasa commented on Sources/NIO/ChannelPipeline.swift
> +                _add($0, position: individualPosition)
I think this needs explicit self.

2020-10-24 07:26 UTC, Lukasa commented
Do we have allocation counter tests that cover this?

2020-10-24 07:27 UTC, Lukasa commented
Never mind, looking at the build failures tells me we do, nice work Peter!

2020-10-26 09:37 UTC, glbrntt requested changes
Nice one! Indentation is off in a handful of places but looks great otherwise.

2020-10-26 09:37 UTC, glbrntt commented on Sources/NIO/ChannelPipeline.swift
> +              position: ChannelPipeline.Position = .last) -> Result<Void, Error> {
Indentation is off here (and for all the `add0` calls in the body too)

2020-10-26 10:29 UTC, Lukasa approved these changes
Once @glbrntt's concerns are addressed I'm happy.

2020-10-27 16:06 UTC, glbrntt approved these changes

2020-10-27 16:14 UTC, merged