ByteBuffer: one fewer allocs to go to Data
apple/swift-nio pull request #1839
Opened 2021-04-30 14:45 UTC by weissi

Motivation:

When getting a `Data` from a `ByteBuffer` we currently allocate twice
(`__DataStorage`) and the closure for `Data.Deallocator`.

Modifications:

We can optimise that by making the closure capture exactly one
`AnyObject` which is already a reference counted object. The compiler
realises that (on Linux) and saves us an alloc.

Thanks @lukasa for the suggestion here: https://github.com/apple/swift-nio/pull/1836#issuecomment-830044155

Result:

Fewer allocs.

2021-04-30 15:26 UTC, Lukasa requested changes

2021-04-30 15:26 UTC, Lukasa commented on IntegrationTests/tests_04_performance/test_01_resources/test_bytebuffer_lots_of_rw.swift
> -            // buffer.writeBytes(foundationData) // see SR-7542
Is this gone on purpose?

2021-04-30 15:26 UTC, Lukasa commented on IntegrationTests/tests_04_performance/test_01_resources/test_bytebuffer_lots_of_rw.swift
> -            buffer.writeBytes(dispatchData) // see https://bugs.swift.org/browse/SR-9597
Similarly, is this gone on purpose?

2021-06-01 11:56 UTC, Lukasa approved these changes

2023-08-17 20:51 UTC, weissi commented
We should resurrect this

2024-11-26 11:36 UTC, merged