Precondition that read doesn't return EINVAL
apple/swift-nio pull request #2022
Opened 2021-12-30 10:50 UTC by FranzBusch

### Motivation:

`read` should never return `EINVAL`. If it does return it though it is a bug inside NIO and we should precondition for it similar to what we do for `EBADF` & `EFAULT`. Closes https://github.com/apple/swift-nio/issues/1339

### Modifications:

This PR adds a new precondition for `EINVAL` and adds test that exercise this precondition.

### Result:

We are now preconditioning against `read` returning `EINVAL`.

2021-12-30 15:40 UTC, weissi commented on IntegrationTests/tests_02_syscall_wrappers/test_02_unacceptable_errnos.sh
> +    for error in EFAULT EBADF, EINVAL; do
The comma isn’t correct here

2021-12-30 15:44 UTC, FranzBusch commented on IntegrationTests/tests_02_syscall_wrappers/test_02_unacceptable_errnos.sh
> +    for error in EFAULT EBADF, EINVAL; do
```suggestion
    for error in EFAULT EBADF EINVAL; do
```

2022-01-03 09:23 UTC, FranzBusch commented
@swift-nio-bot test please

2022-01-03 09:24 UTC, FranzBusch commented
@swift-server-bot test this please

2022-01-04 08:09 UTC, FranzBusch commented
@weissi Do you have any idea why these tests are failing? They are also failing for me locally on main and I cannot figure out why they are returning the wrong value now.

2022-01-04 12:15 UTC, Lukasa commented on IntegrationTests/tests_02_syscall_wrappers/test_02_unacceptable_errnos.sh
> +var whatevs: UInt8 = makeEINVALHappen ? 3021 : 123
This does not produce EINVAL on Posix.write. From the manual page:

```
[EINVAL]           The pointer associated with fildes is negative.
```

`3021` is not negative.

2022-01-04 12:15 UTC, Lukasa commented on IntegrationTests/tests_02_syscall_wrappers/test_02_unacceptable_errnos.sh
> +var whatevs: UInt8 = makeEINVALHappen ? 3021 : 123
It is, however, larger than `UInt8` can hold, so the compile fails. This is why the tests are failing.

2022-01-04 13:03 UTC, Lukasa commented on IntegrationTests/tests_02_syscall_wrappers/test_02_unacceptable_errnos.sh
> +var whatevs: UInt8 = makeEINVALHappen ? -1 : 123
This still won't work. `EINVAL` is triggered by the _pointer_ being negative: this is the `pointee`, and so unaffected. Also, this still won't compile. :smile:

2022-01-04 16:13 UTC, FranzBusch commented on Tests/NIOPosixTests/EventLoopTest+XCTest.swift
> +// Copyright (c) 2017-2022 Apple Inc. and the SwiftNIO project authors
This is currently breaking on the CI and was caused by my previous PR where the CI did not detect this necessary change. I am just going to include it here to fix the CI.

2022-01-04 17:34 UTC, Lukasa requested changes
This change is good, but it's a bit too narrow and a bit too broad.

The original issue only asked to forbid `EINVAL` on `read`. This change adds it to all syscalls in NIOCore, but does not affect those in NIOPosix, which is where the relevant `read` is actually made. As a result, it does not resolve the original issue.

Additionally, the change as written affects _all_ system calls. However, some EINVALs we actually want to tolerate. As an example, see #1030. As a result, we likely need a more complex solution that only adds EINVAL policing to some specific system calls, not all of them.

2022-01-06 10:23 UTC, Lukasa requested changes

2022-01-06 10:23 UTC, Lukasa commented on IntegrationTests/tests_02_syscall_wrappers/test_03_unacceptable_read_errnos.sh
> +## Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
```suggestion
## Copyright (c) 2017-2022 Apple Inc. and the SwiftNIO project authors
```

2022-01-06 10:23 UTC, Lukasa commented on Sources/NIOPosix/System.swift
> +        return try syscall(blocking: true, unacceptableErrnoCodes: defaultUnacceptableErrnoCodes + [EINVAL]) {
Unfortunately I don't think this approach is sufficient for us.

The biggest issue I have here is that this causes a runtime Array allocation on all codepaths through this function. I suspect the performance impact of this is fairly substantial.

Unfortunately, the only really effective solution at the moment is to duplicate the `isUnacceptableErrno` function with a new body. This is what we did for `close`, and sadly is what we have to do here as well.

2022-01-06 10:23 UTC, Lukasa commented on Sources/NIOPosix/System.swift
> +        return try syscall(blocking: true, unacceptableErrnoCodes: defaultUnacceptableErrnoCodes + [EINVAL]) {
Ah, yup, in fact the allocation counter tests failed.

2022-01-06 10:23 UTC, Lukasa commented
@swift-nio-bot test perf please

2022-01-06 10:27 UTC, Lukasa commented
Yup, that report above is not right: those are clearly the results from @weissi's previous PR.

2022-01-06 10:31 UTC, Lukasa commented
@tomerd Seems like the NIO performance builds aren't working again.

2022-01-11 10:25 UTC, Lukasa commented on Sources/NIOPosix/System.swift
> +internal func sysReadCall<T: FixedWidthInteger>(where function: String = #function,
Hmm, I don't love this: it's too specific to `read` (same with those above). Maybe `syscallForbiddingEINVAL`?

2022-01-12 11:45 UTC, Lukasa approved these changes
LGTM, nice one!

2022-01-12 12:16 UTC, merged