Adopt `Sendable` for closures in `HTTPPipelineSetup.swift`
apple/swift-nio pull request #2214
Opened 2022-07-01 11:36 UTC by dnadoba

and fix sendable warnings in tests.

2022-07-01 12:30 UTC, Lukasa requested changes

2022-07-01 12:44 UTC, dnadoba commented on Sources/NIOHTTP1/HTTPPipelineSetup.swift
> +    private func _addHTTPClientHandlers(position: Position = .last,
Fixed in https://github.com/apple/swift-nio/pull/2214/commits/77c2c316d266ce4f1fb26e21d533b82097a865a3

2022-07-01 13:50 UTC, dnadoba commented on Sources/NIOCore/NIOSendable.swift
> +extension UnsafeMutableTransferBox: @unchecked Sendable {}
The changes in `NIOSendable.swift` make `UnsafeTransfer` and `UnsafeMutableTransferBox` available in Swift 5.4. This allows us to unconditionally use them without code duplication and `#if`s.

2022-07-01 13:50 UTC, dnadoba commented on Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
> +@testable import NIOCore
We could also copy & paste `UnsafeTransfer` and `UnsafeMutableTransferBox` into the test target if we don't want to add `@testable`.

2022-07-04 14:37 UTC, Lukasa requested changes

2022-07-04 15:27 UTC, dnadoba commented on Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
> +@testable import NIOCore
Done in https://github.com/apple/swift-nio/pull/2214/commits/8472a2dd92301148daf017eb464ede8ec48f569e

2022-07-05 09:00 UTC, Lukasa approved these changes

2022-07-05 09:01 UTC, merged