rename class Lock to struct NIOLock
apple/swift-nio pull request #2266
Opened 2022-09-08 09:26 UTC by weissi

### Motivation:

It's silly that we allocate _twice_ for each `Lock` because we should just tail-allocate the `pthread_mutex_t`. Unfortunately, that's impossible without changing the API for the worse.

Also `Lock` is a type that can very easily clash with another library.

### Modifications:

- deprecate `Lock`
- introduce `public struct NIOLock` (backed by a `class Storage` for now)

### Result:

- We can file a subsequent issue (easy to implement) which will tail-allocate the `pthread_mutex_t` and we can cut in half all `NIOLock` allocations.

2022-09-08 10:28 UTC, Lukasa requested changes

2022-09-08 10:28 UTC, Lukasa commented on Sources/NIOConcurrencyHelpers/NIOLock.swift
> +public struct NIOLock {
Can we add to this comment that this type has reference semantics?

2022-09-08 10:28 UTC, Lukasa commented on Sources/NIOConcurrencyHelpers/NIOLock.swift
> +#endif
Can we delegate the methods in here to methods on `self._storage`? Swift plays a bit fast and loose with the guarantees around object lifetimes, but in principle we could accidentally `deinit` the lock here after loading it from `_storage`, whereas `self` is generally guaranteed to be alive.

2022-09-13 10:43 UTC, Lukasa commented
@swift-server-bot add to allowlist

2022-09-13 10:44 UTC, Lukasa approved these changes
Nice one, LGTM.

2022-09-13 13:01 UTC, Lukasa approved these changes

2022-09-16 15:42 UTC, Lukasa commented
A couple of deprecation warnings are preventing us merging this.

2022-09-20 16:12 UTC, dnadoba approved these changes

2022-09-21 14:36 UTC, merged

2022-10-04 21:03 UTC, toluRV commented
@weissi @Lukasa  This merge seems to be causing build errors on windows. I created a PR here: https://github.com/apple/swift-nio/pull/2278