Add a pooled recv buffer allocator
apple/swift-nio pull request #2362
Opened 2023-02-03 16:48 UTC by glbrntt

Motivation:

Channels can read `ChannelOptions.maxMessagesPerRead` times from a socket in each read cycle. They typically re-use the same buffer for each read and rely on it CoWing if necessary. If we read more than once in a cycle then we will always CoW the buffer. Instead of reusing one buffer we can reuse a pool of buffers limited by `maxMessagesPerRead` and cycle through each, reducing the chance of CoWing the buffers.

Modifications:

- Add `NIOPoolableRecvByteBufferAllocator` which extends `RecvByteBufferAllocator` to provide the size of the next buffer.
- Add an internal pool which uses a `NIOPoolableRecvByteBufferAllocator`
- Add a wrapper which is either backed by poolable allocator or non-poolable allocator.

Results:

Fewer allocations

2023-02-03 18:16 UTC, Lukasa commented
> If we read more than once in a cycle then we will always CoW the buffer.

Side note: I don't think this is entirely true. It's only true if a `ChannelHandler` holds onto that buffer. Most don't: if they have swift-nio-ssl in the way then it will always drop the inbound buffer.

2023-02-03 19:23 UTC, tomerd commented
@swift-server-bot test this please

2023-02-03 19:26 UTC, tomerd commented
@swift-server-bot test this please

2023-02-03 20:10 UTC, tomerd commented
@swift-server-bot test this please

2023-02-03 20:42 UTC, tomerd commented
@swift-server-bot test this please

2023-02-03 22:00 UTC, tomerd commented
@swift-server-bot test this please

2023-02-06 08:55 UTC, Lukasa requested changes

2023-02-06 08:55 UTC, Lukasa commented on Sources/NIOPosix/PooledRecvBufferAllocator.swift
> +            if let poolable = allocator as? NIOPoolableRecvByteBufferAllocator {
This is pretty painfully expensive. Perhaps we should amend `RecvByteBufferAllocator` to include the new method with a default implementation that returns `nil`, and have a different pooling strategy for the fallback case?

2023-02-06 08:55 UTC, Lukasa commented on Sources/NIOPosix/PooledRecvBufferAllocator.swift
> +                self = .modifying
We shouldn't need a modifying case.

2023-02-06 15:58 UTC, glbrntt commented on Sources/NIOPosix/PooledRecvBufferAllocator.swift
> +        return (self.buffers[index], result)
Good point re: reusing buffers without a CoW; didn't think of that case.

2023-02-13 17:19 UTC, glbrntt commented on Sources/NIOPosix/PooledRecvBufferAllocator.swift
> +        var newBuffer = self.recvAllocator.buffer(allocator: allocator)
Ah, so if the last recorded size wouldn't cause the buffer to grow _and_ the buffer can be reused then we've regressed. Yeah I think we can fix that.

2023-02-13 17:21 UTC, Lukasa commented on Sources/NIOPosix/PooledRecvBufferAllocator.swift
> +        return self.buffer == nil ? self.buffers.count : 1
Yeah that wasn't at all obvious to me. Can you add a comment to that effect?

2023-02-16 17:06 UTC, Lukasa commented on Sources/NIOPosix/BaseStreamSocketChannel.swift
> +                    _ = self.recvBufferPool.record(actualReadBytes: bytesRead)
Can we just not return anything from the record call here?

2023-02-16 17:12 UTC, Lukasa commented on Sources/NIOPosix/PooledRecvBufferAllocator.swift
> +    }
I think this method is beginning to get a bit unwieldy. Can we refactor it into smaller helper functions that each handle one case?

2023-02-20 14:57 UTC, Lukasa approved these changes
Nice one, thanks @glbrntt!

2023-02-20 17:00 UTC, merged