`Embedded`: `getOption(ChannelOptions.allowRemoteHalfClosure)` should not `fatalError`
apple/swift-nio pull request #2429
Opened 2023-05-17 14:48 UTC by felixschlegel

## Motivation

[In `swift-nio-ssl`, I am currently working on allowing half-closures](https://github.com/apple/swift-nio-ssl/pull/428/) which rely on querying the underlying channel if `ChannelOptions.Types.AllowRemoteHalfClosureOption` is enabled. As a lot of
`swift-nio-ssl`'s tests rely on `EmbeddedChannel`, which did not support this option, they failed failed due to a `fatalError`.

## Modifications

* add a `public var allowRemoteHalfClosure` to `EmbeddedChannel`
* enable setting/getting
  `ChannelOptions.Types.AllowRemoteHalfClosureOption` in
`EmbeddedChannel` (only modifies the `allowRemoteHalfClosure` variable
* add test for new behaviour

2023-05-17 14:56 UTC, Lukasa requested changes

2023-05-17 14:56 UTC, Lukasa commented on Sources/NIOEmbedded/Embedded.swift
> +        || option is ChannelOptions.Types.AllowRemoteHalfClosureOption {
I know I gave you this advice, so this is really my fault, but I no longer think this behaviour is quite right. 😁 

I think we should allow the user of `EmbeddedChannel` to have a `public var` that they can set which provides the value of `AllowRemoteHalfClosureOption`. That lets tests configure whether the behaviour should be supported or not. This also lets us support `setOption` for this option.

Relatedly, the default value should be `false`.

2023-05-19 08:19 UTC, Lukasa requested changes
Great, this looks really good. Can I ask you to make the same enhancement to `AsyncTestingChannel` as well? That will keep the two interfaces in step.

2023-05-19 08:19 UTC, Lukasa commented on Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
> +        XCTAssertEqual(try options?.getOption(ChannelOptions.allowRemoteHalfClosure), true)
Can you extend this test to add a case for changing the value of `allowRemoteHalfClosure` on the `EmbeddedChannel` directly?

2023-05-19 13:36 UTC, felixschlegel commented on Sources/NIOEmbedded/AsyncTestingChannel.swift
> +    public var allowRemoteHalfClosure: Bool = false
Thanks for pointing that out! Have moved `allowRemoteClosure` to `EmbeddedChannelCore` now!

2023-05-19 14:17 UTC, Lukasa approved these changes
Fantastic!

2023-05-19 14:17 UTC, Lukasa commented
@swift-server-bot add to allowlist

2023-05-19 15:07 UTC, Lukasa commented
Can you update the allocation limits?

2023-05-19 15:44 UTC, Lukasa approved these changes

2023-05-19 16:47 UTC, merged