Fix overflow
apple/swift-nio pull request #2543
Opened 2023-10-09 22:48 UTC by LorenzoFritzsch

Fixes overflow when initializing any `TimeAmount` other than `TimeAmount.nanoseconds` to `Int64.max`.

### Motivation:

Closes https://github.com/apple/swift-nio/issues/2532

### Modifications:

Added a check to the amount calculated in nanoseconds. If it overflows, `TimeAmount(.max)` is returned, otherwise `TimeAmount(nanoseconds)`.

### Result:
Program doesn't crash when setting a `TimeAmount` to be `Int64.max`. Instead, `TimeAmount(.max)` is returned.

2023-10-10 07:02 UTC, glbrntt requested changes

2023-10-10 07:02 UTC, glbrntt commented on Sources/NIOCore/EventLoop.swift
> +        return nanoseconds >= 0 ? TimeAmount(nanoseconds) : TimeAmount(.max)
This isn't quite right: `TimeAmount` can represent a negative duration so `.microseconds(-1000)` would be incorrectly converted to `.max`. We'd also need to have unit tests for the extreme (overflow and underflow) cases to verify this behaves as expected.

2023-10-10 13:59 UTC, Lukasa requested changes
As noted by @weissi 's comment in the linked issue, it would also be better to replace the unchecked operations by `reportingOverflow` methods.

2023-10-11 09:30 UTC, glbrntt commented on Tests/NIOPosixTests/EventLoopTest.swift
> +    }
Sorry to be a pain, but could you move these to https://github.com/apple/swift-nio/blob/main/Tests/NIOCoreTests/TimeAmountTests.swift?

2023-10-12 07:05 UTC, glbrntt commented
@swift-server-bot test this please

2023-10-12 09:59 UTC, glbrntt approved these changes

2023-10-12 13:39 UTC, Lukasa approved these changes
Nice, this looks really good to me. Let's get the tests running.

2023-10-12 13:39 UTC, Lukasa commented
@swift-server-bot test this please

2023-10-12 14:07 UTC, merged