Remove surplus Sendable requirements from FileSystem with methods
apple/swift-nio pull request #2706
Opened 2024-04-23 12:58 UTC by PeterAdams-A

Motivation:

Many of the filesystem with methods have a requirement that the result type is sendable.  In most cases this is not required as the result is not shared or sent.

Modifications:

Remove sendable requirement for result types where it is not required.

Result:

Users will not have to make so many types sendable.

2024-04-23 13:12 UTC, Lukasa approved these changes

2024-04-23 13:55 UTC, glbrntt requested changes

2024-04-23 13:55 UTC, glbrntt commented on Sources/NIOFileSystem/FileSystemProtocol.swift
> +    public func withFileHandle<R>(
I think the one on L336 also needs to be done

2024-04-23 14:59 UTC, glbrntt approved these changes

2024-04-23 15:48 UTC, PeterAdams-A commented
@swift-nio-bot test failed

2024-04-23 15:52 UTC, PeterAdams-A commented
@swift-server-bot test this please

2024-04-24 09:35 UTC, glbrntt commented
These are all okay because they widen the constraint:

```
16:55:46   💔 API breakage: func WritableFileHandleProtocol.withBufferedWriter(startingAtAbsoluteOffset:capacity:execute:) has generic signature change from <Self, R where Self : _NIOFileSystem.WritableFileHandleProtocol, R : Swift.Sendable> to <Self, R where Self : _NIOFileSystem.WritableFileHandleProtocol>
16:55:46   💔 API breakage: func DirectoryFileHandleProtocol.withFileHandle(forReadingAt:options:execute:) has generic signature change from <Self, R where Self : _NIOFileSystem.DirectoryFileHandleProtocol, R : Swift.Sendable> to <Self, R where Self : _NIOFileSystem.DirectoryFileHandleProtocol>
16:55:46   💔 API breakage: func DirectoryFileHandleProtocol.withFileHandle(forWritingAt:options:execute:) has generic signature change from <Self, R where Self : _NIOFileSystem.DirectoryFileHandleProtocol, R : Swift.Sendable> to <Self, R where Self : _NIOFileSystem.DirectoryFileHandleProtocol>
16:55:46   💔 API breakage: func DirectoryFileHandleProtocol.withFileHandle(forReadingAndWritingAt:options:execute:) has generic signature change from <Self, R where Self : _NIOFileSystem.DirectoryFileHandleProtocol, R : Swift.Sendable> to <Self, R where Self : _NIOFileSystem.DirectoryFileHandleProtocol>
16:55:46   💔 API breakage: func DirectoryFileHandleProtocol.withDirectoryHandle(atPath:options:execute:) has generic signature change from <Self, R where Self : _NIOFileSystem.DirectoryFileHandleProtocol, R : Swift.Sendable> to <Self, R where Self : _NIOFileSystem.DirectoryFileHandleProtocol>
16:55:46   💔 API breakage: func withFileSystem(numberOfThreads:_:) has generic signature change from <R where R : Swift.Sendable> to <R>
16:55:46   💔 API breakage: func FileSystemProtocol.withFileHandle(forReadingAt:options:execute:) has generic signature change from <Self, R where Self : _NIOFileSystem.FileSystemProtocol, R : Swift.Sendable> to <Self, R where Self : _NIOFileSystem.FileSystemProtocol>
16:55:46   💔 API breakage: func FileSystemProtocol.withFileHandle(forWritingAt:options:execute:) has generic signature change from <Self, R where Self : _NIOFileSystem.FileSystemProtocol, R : Swift.Sendable> to <Self, R where Self : _NIOFileSystem.FileSystemProtocol>
16:55:46   💔 API breakage: func FileSystemProtocol.withFileHandle(forReadingAndWritingAt:options:execute:) has generic signature change from <Self, R where Self : _NIOFileSystem.FileSystemProtocol, R : Swift.Sendable> to <Self, R where Self : _NIOFileSystem.FileSystemProtocol>
16:55:46   💔 API breakage: func FileSystemProtocol.withDirectoryHandle(atPath:options:execute:) has generic signature change from <Self, R where Self : _NIOFileSystem.FileSystemProtocol, R : Swift.Sendable> to <Self, R where Self : _NIOFileSystem.FileSystemProtocol>
```

These are SPI so fine to ignore:
```
16:55:46   💔 API breakage: func withUncancellableTearDown(_:tearDown:) has generic signature change from <R where R : Swift.Sendable> to <R>
16:55:46   💔 API breakage: func withUncancellableTearDown(_:tearDown:) has parameter 1 type change from (Swift.Result<R, Swift.Error>) async throws -> Swift.Void to (Swift.Result<Swift.Void, Swift.Error>) async throws -> Swift.Void
```

2024-04-24 09:36 UTC, merged