Make EventLoopPromise conform to Equatable
apple/swift-nio pull request #2714
Opened 2024-05-03 17:18 UTC by gjcairo

This PR conforms `EventLoopPromise` to the `Equatable` protocol.

### Motivation:

`EventLoopPromise` is not currently `Equatable`, whereas the underlying `EventLoopFuture` is.
For consistency, it makes sense for `EventLoopPromise` to conform to `Equatable` too.

### Modifications:

Conform `EventLoopPromise` to `Equatable`. This is trivial, as the only property is the underlying `EventLoopFuture`, which is already `Equatable`.

### Result:

`EventLoopPromise` is now `Equatable`.

2024-05-07 15:45 UTC, Lukasa requested changes
Mind adding some tests here Gus?

2024-06-27 07:24 UTC, dnadoba requested changes
This is a bad idea. Promise can change at any time, violating all requirements of Equatable, including the most basic one:
a == a is always true (Reflexivity)

we should deprecate the existing conformance.

2024-06-27 07:27 UTC, dnadoba approved these changes
Never mind, it is based on identity, not on the actual value of the promise which is fine.

2024-06-27 15:26 UTC, Lukasa approved these changes

2024-07-31 14:01 UTC, merged