testSimpleMPTCP should not fail for ENOPROTOOPT
apple/swift-nio pull request #2725
Opened 2024-05-22 14:58 UTC by rnro

### Motivation:

MPTCP implementations are permitted to return `ENOPROTOOPT` if MPTCP has been disabled. This should not report as a test failure.

Source: https://www.mptcp.dev/implementation.html

### Modifications:

Instead of failing the test, log the permitted error and return.

### Result:

No more misleading testSimpleMPTCP test failures

2024-05-22 15:08 UTC, Lukasa requested changes
I think you got the conditional a bit screwy here.

2024-05-22 15:53 UTC, rnro commented
> I think you got the conditional a bit screwy here.

Don't code and dash kids. It was very screwy. I have amended it and run all NIO tests locally in a Swift 5.10 Docker container.

2024-05-22 15:54 UTC, Lukasa approved these changes

2024-05-23 06:47 UTC, rnro commented
@swift-server-bot test this please

2024-05-23 09:07 UTC, merged