Provide a default CopyStrategy overload for copyItem.
apple/swift-nio pull request #2818
Opened 2024-07-30 14:08 UTC by UncleMattHope

FilesystemProtocol/copyItem has an overload providing the default CopyStrategy

### Motivation:

Based on user feedback from #2806 
This makes it easier to use, especially when copying files such that it is irrelevant.

### Modifications:

Add overload providing ```(at:to:shouldProceedAfterError:shouldCopyItem:)``` with ```CopyStrategy.platformDefault```
as the strategy.

### Result:

A simpler and more robust to change API will exist for ```copyItem()```

2024-07-30 14:14 UTC, weissi approved these changes
Thank you!

2024-07-30 14:51 UTC, glbrntt requested changes

2024-07-30 14:51 UTC, glbrntt commented on Sources/NIOFileSystem/FileSystemProtocol.swift
> +    func copyItem(
Needs a `public`!

2024-07-30 15:14 UTC, glbrntt approved these changes

2024-07-31 18:23 UTC, UncleMattHope commented on Sources/NIOFileSystem/Internal/ParallelDirCopy.swift
> +                        // To accurately propagate the cancellation we must check here too
This fixes the flaky test, and makes cancellation reliable.

2024-07-31 18:24 UTC, UncleMattHope commented on Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
> +        // Whitebox testing to cover specific scenarios
This makes the test non flaky (it reliably fails without the fix)

2024-07-31 19:32 UTC, glbrntt approved these changes

2024-08-01 09:13 UTC, merged