Adopt `NIOThrowingAsyncSequenceProducer`
apple/swift-nio pull request #2879
Opened 2024-09-10 14:23 UTC by rnro

### Motivation:

Adopt `NIOThrowingAsyncSequenceProducer` in NIOFileSystem to reduce code duplication.

### Modifications:

Adopt `NIOThrowingAsyncSequenceProducer` in NIOFileSystem `DirectoryEntryProducer` and `FileChunkProducer`

### Result:

No functional changes. Internal changes reduce code duplication.

2024-09-11 09:53 UTC, FranzBusch reviewed
In general this looks good to me. Have you run some benchmarks between the two to make sure we still have the same performance?

2024-09-11 13:27 UTC, glbrntt requested changes
This looks good! I left a couple of small comments which need addressing.

2024-09-11 13:27 UTC, glbrntt commented on Sources/NIOFileSystem/DirectoryEntries.swift
> +extension NIOThrowingAsyncSequenceProducer where Element == [DirectoryEntry], Failure == Error,
nit
```suggestion
extension NIOThrowingAsyncSequenceProducer where Element == [DirectoryEntry], Failure == (any Error),
```

2024-09-11 13:27 UTC, glbrntt commented on Sources/NIOFileSystem/DirectoryEntries.swift
> +            self.state = .modifying
`.modifying` isn't required here because we aren't modifying any of the state held in the `openPausedProducing` case

2024-09-11 13:27 UTC, glbrntt commented on Sources/NIOFileSystem/DirectoryEntries.swift
> +            self.state = .modifying
same here, no need to do `.modifying`

2024-09-11 13:27 UTC, glbrntt commented on Sources/NIOFileSystem/DirectoryEntries.swift
> +        case .open(let nIOThreadPool, let source, let array):
nit: `threadPool`

2024-09-11 13:27 UTC, glbrntt commented on Sources/NIOFileSystem/FileChunks.swift
> +
nit: no blank lines at the start of funcs
```suggestion
    init(range: FileChunks.ChunkRange, handle: SystemFileHandle, length: Int64) {
```

2024-09-11 13:27 UTC, glbrntt commented on Sources/NIOFileSystem/FileChunks.swift
> +        }
Hmm, I don't think our minimum Swift version is new enough to support this? Also the indentation is way off for the body of each case.

2024-09-11 13:27 UTC, glbrntt commented on Sources/NIOFileSystem/FileChunks.swift
> +        }
(Also I really don't like this syntax but maybe I'm just a curmudgeon...)

2024-09-11 13:27 UTC, glbrntt commented on Sources/NIOFileSystem/FileChunks.swift
> +    mutating func updateRange(count: Int) -> Bool {
It's not obvious _how_ the range is updated without looking at the implementation, also the return value is quite misleading: `if updateRange(count: blah) { ... }` looks a whole lot like "if the range was updated then ...".

Would probably be clearer if you call this `didReadBytes(_ count: Int)` and documented the return value (you could use an enum for the return type but that's probably overkill)

2024-09-11 13:29 UTC, glbrntt commented
> In general this looks good to me. Have you run some benchmarks between the two to make sure we still have the same performance?

I would be surprised if there was a substantial difference. You'd think the syscalls would dominate here but it's worth doing some validation nonetheless.

2024-09-13 09:04 UTC, glbrntt approved these changes
Looks good modulo some failing CI!

2024-09-13 09:04 UTC, glbrntt commented on Sources/NIOFileSystem/FileChunks.swift
> +            self.state.withLockedValue { state in state.pauseProducing()}
```suggestion
            self.state.withLockedValue { state in state.pauseProducing() }
```

2024-09-13 13:18 UTC, rnro commented
Performance-wise there doesn’t seem to be much of a difference.

I tested listing the files on disk, exercising the `DirectoryEntries` path. I listed a directory I happened to have with 772492 files in it making up 23GiB.

For the existing code:
3 runs of: 27.51s, 26.53s, 26.34s
With an average of:  26.8s

For the new code:
3 runs of: 26.08s, 27.71s, 27.35s
With an average of:  27.05s

2024-09-13 13:20 UTC, FranzBusch approved these changes

2024-09-13 13:21 UTC, merged

2024-09-17 13:35 UTC, finagolfin commented
This pull consistently causes hanging `FileHandle` tests in my Android CI, that runs them in an Android x86_64 emulator on both [linux](https://github.com/finagolfin/swift-android-sdk/actions/runs/10899962069/job/30246566565#step:38:1288) and [macOS](https://github.com/finagolfin/swift-android-sdk/actions/runs/10861194727/job/30142820028#step:38:2747) built with 5.10, 6.0, and trunk 6.1. I can reproduce locally on Android 13 AArch64 with a recently-built trunk 6.1 toolchain from the Sep. 4 source snapshot and [the Termux 5.10.1 toolchain](https://github.com/termux/termux-packages/blob/master/packages/swift/build.sh).

I'll see if I can track it down and file an issue.