Add concrete description for `EmbeddedEventLoop`
apple/swift-nio pull request #2890
Opened 2024-09-19 09:32 UTC by aryan-25

### Motivation:

We want to avoid going through `EventLoopGroup`'s [`String(describing: self)`](https://github.com/apple/swift-nio/blob/8307ad610a358513b2190955379829d70f04b8c2/Sources/NIOCore/EventLoop.swift#L414) when obtaining the description of an `EventLoopGroup` or `EventLoop`.

The  concrete `MultiThreadedEventLoopGroup` and `SelectableEventLoop` already implement a `description` property. `EmbeddedEventLoop` does not.

### Modifications:

Added a concrete description property in `EmbeddedEventLoop`.

### Result:

The description of `EmbeddedEventLoop` can be obtained without going through `String(describing: self)`.

2024-09-19 11:14 UTC, FranzBusch approved these changes

2024-09-19 11:40 UTC, Lukasa approved these changes

2024-09-19 11:58 UTC, glbrntt requested changes

2024-09-19 11:58 UTC, glbrntt commented on Sources/NIOEmbedded/Embedded.swift
> +    public var description = "EmbeddedEventLoop"
This should be a `let`!

2024-09-19 13:03 UTC, glbrntt approved these changes

2024-09-20 12:19 UTC, merged

2024-09-30 21:53 UTC, weissi commented on Sources/NIOEmbedded/Embedded.swift
> +    public let description = "EmbeddedEventLoop"
This should maybe include the pointer value of `self`? Just so we can distinguish them