[NIOFileSystem] Provide an API to specify allowing unlimited sized reads
apple/swift-nio pull request #2914
Opened 2024-10-10 15:54 UTC by clintonpi

Motivation:

As described in issue [#2877](https://github.com/apple/swift-nio/issues/2877), there is no API available to specify allowing a read of unlimited size.

Modifications:

- Add a new `public static` property, `unlimited`, to `ByteCount` representing an unlimited amount of bytes.
- Adapt `ReadableFileHandleProtocol.readToEnd(fromAbsoluteOffset:maximumSizeAllowed:)` to work with `maximumSizeAllowed` being `ByteCount.unlimited`.

Result:

An API to specify allowing a read of an unlimited size will be available.

2024-10-11 08:17 UTC, glbrntt requested changes
One nit but looks great otherwise

2024-10-11 08:17 UTC, glbrntt commented on Sources/NIOFileSystem/FileHandleProtocol.swift
> +        }
We can do this in a one line to keep `maximumSizeAllowed` constant:

```swift
let maximumSizeAllowed = maximumSizeAllowed == .unlimited ? .byteBufferCapacity : maximumSizeAllowed
```

2024-10-11 08:31 UTC, glbrntt approved these changes

2024-10-11 09:25 UTC, merged

2024-10-14 08:59 UTC, weissi commented on Tests/NIOFileSystemIntegrationTests/XCTestExtensions.swift
> +func XCTAssertNoThrowAsync<T>(
we shouldn't squat on XCTest's `XCT*` name space, you can make it `NIOAssertNoThrowAsync` or smth